---
downloads: ~/.ansible-downloads/
gitmod_accept_newhostkey: true


configure_dotfiles: true
dotfiles_repo: https://github.com/mrolli/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_local_destination: "{{ ansible_env.HOME }}/.dotfiles"


configure_dock: true
dockitems_remove:
 - Launchpad
 - TV
dockitems_persist: []


configure_macos: true
macos_script: "~/.macos --no-restart"

configure_apps: true
nvim_config_repo: https://github.com/mrolli/nvim.config.git

configure_usershell: true
# default_usershell: "{{ homebrew_prefix}}/bin/bash"
default_usershell: "/bin/zsh"

homebrew_taps:
  - homebrew/cask-fonts
  - hashicorp/tap

homebrew_installed_packages:
  #  - asciinema
  - azure-cli
  - bash
  - bash-completion@2
  - bat
  - ca-certificates
  #  - composer
  - coreutils
  - ctags
  - dos2unix
  #  - duti
  - exiftool
  - fd
  #  - ffmpeg
  - findutils
  - fswatch
  - fzf
  - gd
  - gettext
  - gh
  - git
  - glib
  - glow
  - gnu-sed
  - gnupg
  #  - go
  - grip
  - harfbuzz
  - imagemagick
  - lazygit
  #  - mariadb
  - mas
  - moreutils
  #  - mysql-client
  #  - mycli
  - neofetch
  - neovim
  - node
  - ollama
  - p7zip
  - hashicorp/tap/packer
  - hashicorp/tap/terraform
  - terraform-docs
  #  - php
  - pinentry-mac
  - pnpm
  - podman
  - pstree
  - ripgrep
  - rsync
  - rubberband
  - shellcheck
  - starship
  - stow
  - telnet
  - tealdeer
  - tmux
  - tmux-mem-cpu-load
  - tmuxp
  #  - vim
  - wallpaper # used by theme switcher
  - watch
  - webp # for handling webp images
  - wget
  - xz
  - yarn
  - youtube-dl

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  #  - alacritty
  - 1password-cli
  - 1password
  #  - ableton-live-suite10
  - alfred
  - appcleaner
  # - homebrew/cask/docker
  - firefox
  - font-jetbrains-mono
  - font-symbols-only-nerd-font
  - gitx
  #  - gray
  #  - guitar-pro
  #  - horos
  - iina
  - keycastr
  - miniconda
  #  - native-access
  #  - omnigraffle
  - protonvpn
  - rar
  - spotify
  #  - sequel-pro
  #  - textmate
  #  - vagrant
  #  - vcv-rack
  #  - virtualbox
  #  - virtualbox-extension-pack
  #  - webex-meetings
  - wezterm
#  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1569813296, name: "1Password for Safari" }
  - { id: 1440147259, name: "AdGuard for Safari (Safari Extension)" }
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 425264550, name: "Blackmagic Disk Speed Test" }
  - { id: 1453365242, name: "Brother P-touch Editor" }
  #- { id: 1482920575, name: "DuckDuckGo Privacy Essentials" }
  - { id: 1500241909, name: "iFinance 5" }
  #- { id: 408981434, name: "iMovie" }
  #- { id: 408981434, name: "iMovie 9.0.9" }
  - { id: 6472865291, name: "Keymapp" }
  #- { id: 634148309, name: "Logic Pro X" }
  - { id: 430255202, name: "Mactracker" }
  #- { id: 1295203466, name: "Microsoft Remote Desktop 10" }
  #- { id: 1041465860, name: "Model 15" }
  #- { id: 823766827, name: "OneDrive" }
  - { id: 764936294, name: "Purple Tree" }
  #- { id: 1315583175, name: "Recipe Keeper" }
  - { id: 409907375, name: "Remote Desktop" }
  - { id: 1573919086, name: "Total Refresh (Safari Extension)" }
  - { id: 1480933944, name: "Vimari (Safari Extension)" }
  - { id: 1230249825, name: "VMware Remote Console" }

mas_email: ""
mas_password: ""
