---
downloads: ~/.ansible-downloads/
gitmod_accept_newhostkey: true


configure_dotfiles: true
dotfiles_repo: https://github.com/mrolli/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_local_destination: "{{ ansible_env.HOME }}/.dotfiles"


configure_dock: true
dockitems_remove:
 - Launchpad
 - TV
dockitems_persist: []


configure_macos: true
macos_script: "~/.macos --no-restart"

# Install homebrew packages from Brewfile
homebrew_use_brewfile: true
homebrew_brewfile_dir: "{{ inventory_dir }}"
