---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    - import_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ["dotfiles"]

    - import_tasks: tasks/macos.yml
      when: configure_macos
      tags: ["macos"]

    - import_tasks: tasks/nvim.yml
      when: configure_apps
      tags: ["nvim"]

    - block:
        - name: Uptime
          ansible.builtin.shell: uptime
          register: uptime
          changed_when: false

        - name: Output hostname and uptime
          ansible.builtin.debug:
            msg: "{{ ansible_hostname }}: {{ uptime.stdout }}"
      tags: ["post"]

- name: Run dotfiles' Ansible playbook
  import_playbook: "{{ lookup('ansible.builtin.env', 'HOME') }}/.dotfiles/ansible/main.yml"
  become: false
  tags: ["dotfiles"]
