---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    - name: Ensure dotfiles repository is cloned locally.
      ansible.builtin.git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_repo_local_destination }}"
        version: "{{ dotfiles_repo_version }}"
        accept_newhostkey: "{{ gitmod_accept_newhostkey }}"
        update: false
      become: false
      when: configure_dotfiles
      tags: ["dotfiles"]

    - name: Run .macos in dotfiles.
      command: "{{ macos_script }}"
      changed_when: false
      when: configure_macos
      tags: ["macos"]

- name: Run dotfiles' Ansible playbook
  import_playbook: "{{ lookup('ansible.builtin.env', 'HOME') }}/.dotfiles/ansible/main.yml"
  become: false
  tags: ["dotfiles", "post"]
