---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.mac.mas
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

  - name: Uptime
    ansible.builtin.shell: uptime
    register: uptime
    changed_when: false

  - name: Output hostname and uptime
    ansible.builtin.debug:
      msg: "{{ hostname.stdout }}: {{ uptime.stdout }}"

