---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
  - name: Ooutput hostname
    shell:
      cmd: hostname -f
    register: hostname
    changed_when: false

  - name: Uptime
    ansible.builtin.shell: uptime
    register: uptime
    changed_when: false

  - name: Output hostname and uptime
    ansible.builtin.debug:
      msg: "{{ hostname.stdout }}: {{ uptime.stdout }}"

