---
- name: Ensure dotfiles repository is cloned locally.
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_newhostkey: "{{ gitmod_accept_newhostkey }}"
    update: false
  become: false

- name: Call dotfiles' bootstrap script.
  command: "{{ dotfiles_repo_local_destination }}/bootstrap"
  changed_when: false
  become: false
