---
- name: (iTerm2) Set LoadPrefsFromCustomFolder
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: int
    value: 1

- name: (iterm2) Set prefs file location
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key:  PrefsCustomFolder
    type: string
    value: "{{ dotfiles_repo_local_destination }}/iterm2/"

- name: (iterm2) Set saving preferences to manual
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: NoSyncNeverRemindPrefsChangesLostForFile_selection
    type: int
    value: 1

- name: (iterm2) Enable automatic update checks
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: SUEnableAutomaticChecks
    type: int
    value: 1
