---
- name: Register current user shell.
  ansible.builtin.command: dscl . -read ~/ UserShell
  register: current_usershell
  changed_when: false

- name: Check if expected usershell is installed
  ansible.builtin.command: '[ -x "{{ default_usershell }}" ]'
  register: usershell_available
  changed_when: false
  failed_when: "usershell_available.rc != 0"

- name: Make usershell avaialble as login shell if needed.
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ default_usershell }}"
    state: present
  become: true

- name: Set user shell to {{ default_usershell }}
  ansible.builtin.command: chsh -s "{{ default_usershell }}" "{{ ansible_user_id }}"
  when: default_usershell not in current_usershell.stdout
  become: true

- name: "Manage shell configuration for zsh"
  block:
  - name: Fetch my configuration repo for zsh
    ansible.builtin.git:
      repo: "{{ zsh_config_repo_url }}"
      dest: "{{ zsh_config_repo_dest }}"
      accept_newhostkey: true

  - name: Symlink zshenv to home directory
    ansible.builtin.file:
      src: "{{ zsh_config_repo_dest }}/zshenv"
      dest: ~/.zshenv
      owner: "{{ ansible_user }}"
      group: staff
      state: link
      force: true
  when: default_usershell == "/bin/zsh"
